#pragma once

#define TILE_SIZE 32

#define SCREEN_WIDTH 1920
#define SCREEN_HEIGHT 1080

#define SCREEN_TILE_X (SCREEN_WIDTH / TILE_SIZE)
#define SCREEN_TILE_Y (SCREEN_HEIGHT / TILE_SIZE)

// MAP
#define TILE_FLOOR 0
#define TILE_WALL 1
#define TILE_DOOR 2

#define WAITINGMAP_ROWS (SCREEN_HEIGHT / TILE_SIZE)
#define WAITINGMAP_COLS (SCREEN_WIDTH / TILE_SIZE)

#define HALLWAYMAP_ROWS (int)(WAITINGMAP_ROWS * 1.5f)
#define HALLWAYMAP_COLS (int)(WAITINGMAP_COLS * 1.5f)

#define BOSSMAP_ROWS (int)(WAITINGMAP_ROWS * 2.0f)
#define BOSSMAP_COLS (int)(WAITINGMAP_COLS * 2.0f)

#define WAITING_X   0
#define HALLWAY1_X  (WAITINGMAP_COLS * TILE_SIZE)
#define BOSS1_X     (HALLWAY1_X + HALLWAYMAP_COLS * TILE_SIZE)
#define HALLWAY2_X  (BOSS1_X   + BOSSMAP_COLS    * TILE_SIZE)
#define BOSS2_X     (HALLWAY2_X + HALLWAYMAP_COLS * TILE_SIZE)
#define HALLWAY3_X  (BOSS2_X   + BOSSMAP_COLS    * TILE_SIZE)
#define BOSS3_X     (HALLWAY3_X + HALLWAYMAP_COLS * TILE_SIZE)

#define MAX_MAP_ROWS 128
#define MAX_MAP_COLS 256
#define MAX_DOORS 16

// PLAYER
#define PLAYER_SIZE 32
#define PLAYER_HITBOX_SIZE 28
#define PLAYER_SPEED 14.8f
#define PLAYER_INVINCIBLE_TIME 60

// ENEMY
#define ENEMY_SIZE 32
#define ENEMY_HITBOX_SIZE 28
#define ENEMY_HP 30
#define ENEMY_LIMIT 1

#define ENEMY_COLS_SPAWN_MARGIN 20
#define ENEMY_ROWS_SPAWN_MARGIN 5

#define ENEMY_MOVE 120

#define ENEMY_CHASE_RANGE 200.0f
#define ENEMY_SPEED 2.5f

#define CAT_PAW_SIZE 25
#define CAT_PAW_SPEED 5.0f
#define CAT_PAW_DAMAGE 10
#define CAT_PAW_LIMIT (ENEMY_LIMIT * 2)
#define CAT_PAW_INTERVAL 180

// BOSS
#define BOSS_SIZE (TILE_SIZE * 6)
#define BOSS_HP 500
#define BOSS_PAW_SIZE 64
#define BOSS_PAW_SPEED 10.0f
#define BOSS_PAW_INTERVAL 180
#define BOSS_PAW_LIMIT 50

#define DASH_WARN_TILES 100
#define DASH_WARN_INTERVAL 100
#define DASH_SPEED 18.0f
#define DASH_INTERVAL 100

#define BOSS_ATTACK_INTERVAL 20

// BULLET
#define BULLET_MAX 50
#define BULLET_SPEED 8.0f
#define BULLET_DAMAGE 10
#define KNOCKBACK_FORCE 6.0f
#define KNOCKBACK_TIME 10
#define BULLET_SPEED 8.0f