#pragma once

#define TILE_SIZE 32

#define PLAYER_SIZE 32

#define ENEMY_SIZE 32
#define ENEMY_LIMIT 50

#define BOSS_SIZE (32 * 3)

#define SCREEN_WIDTH 1920
#define SCREEN_HEIGHT 1080

#define SCREEN_TILE_X (SCREEN_WIDTH / TILE_SIZE)
#define SCREEN_TILE_Y (SCREEN_HEIGHT / TILE_SIZE)

// -----------------MAP------------------------
#define TILE_FLOOR 0
#define TILE_WALL 1
#define TILE_DOOR 2

#define WAITINGMAP_ROWS (SCREEN_HEIGHT / TILE_SIZE)
#define WAITINGMAP_COLS (SCREEN_WIDTH / TILE_SIZE)

#define FIRST_HALLWAYMAP_ROWS (int)(WAITINGMAP_ROWS * 1.5f)
#define FIRST_HALLWAYMAP_COLS (int)(WAITINGMAP_COLS * 1.5f)
#define FIRST_HALLWAYMAP_X (WAITINGMAP_COLS * TILE_SIZE)