#pragma once

enum { STOP, MOVE };
enum { INACTIVE, ACTIVE };

// MAP
typedef enum { MAP_WAITING, MAP_FIRST_HALLWAY, MAP_FIRST_BOSS, MAP_SECOND_HALLWAY, MAP_SECOND_BOSS, MAP_THIRD_HALLWAY, MAP_THIRD_BOSS } MAP_TYPE;
typedef enum { DOOR_CLOSE, DOOR_OPEN } DOOR_STATE;

// ENEMY
typedef enum { ENEMY_IDLE, ENEMY_CHASE, ENEMY_RANGED } ENEMY_STATE;

// BOSS
typedef enum { BOSS_IDLE, BOSS_CHASE, BOSS_RANGED } BOSS_STATE;