#pragma once

enum { INACTIVE, ACTIVE };

// MAP
typedef enum { MAP_WAITING, MAP_FIRST_HALLWAY, MAP_FIRST_BOSS, MAP_SECOND_HALLWAY, MAP_SECOND_BOSS, MAP_THIRD_HALLWAY, MAP_THIRD_BOSS } MAP_TYPE;
typedef enum { DOOR_CLOSE, DOOR_OPEN } DOOR_STATE;

// PLAYER
typedef enum { PLAYER_IDLE, PLAYER_MOVE, PLAYER_HIT, PLAYER_DEAD } PLAYER_STATE;

// ENEMY
typedef enum { ENEMY_IDLE, ENEMY_CHASE, ENEMY_MELEE, ENEMY_RANGED, ENEMY_HIT, ENEMY_DEAD } ENEMY_STATE;

// BOSS
typedef enum { BOSS_IDLE, BOSS_MOVE, BOSS_CHASE, BOSS_HIT, BOSS_DEAD } BOSS_STATE;
typedef enum { BOSS_DASH, BOSS_MELEE, BOSS_THREE_WAY_CATPAW, BOSS_CIRCULAR_CATPAW, BOSS_JUMP, BOSS_RANDOM_CATPAW } BOSS_SKILL_STATE;